idf_component_register(
    SRCS
        "sx1262_radio.c"
        "sx1262_radio_timing.c"
        "sx1262_radio_backend_common.c"
        "sx1262_radio_backend_esp.c"
        "vendor/semtech_sx126x_driver/sx126x.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "private_include"
        "vendor/semtech_sx126x_driver"
    REQUIRES
        node_common
    PRIV_REQUIRES
        esp_driver_gpio
        esp_driver_spi
        esp_timer
        freertos
)
