-- Generated from receiver/schemas/receiver_enums.json,
-- receiver/schemas/receiver_entities.json, and
-- receiver/db/schema_source.sql by receiver/tools/generate.py.
-- Do not edit this file by hand.
-- Receiver enum manifest SHA-256: f4605c7c919915a317ffa6b7a5ad8f90448b33acb53dcbc16f1af0cfa96b493e
-- Receiver entity manifest SHA-256: 342ceabaa737daf5134149d3802d0e0a87f1a3d862b10dd55e15726c6161af41
-- Handwritten schema source SHA-256: 17d8dbed9bde0f1941797533a3d818f0e2531aa872679ac7e1663d40bf2dd087

-- Handwritten receiver database schema source.
--
-- receiver/tools/generate.py appends generated enum catalogues and entity
-- tables to this source to produce schema.sql. The initializer owns the
-- surrounding transaction, sets PRAGMA application_id, and inserts the one
-- metadata row only after it has verified the exact schema.sql fingerprint
-- expected by the application.

CREATE TABLE database_metadata (
    singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),
    group_id BLOB NOT NULL CHECK (length(group_id) = 8),
    database_schema_version INTEGER NOT NULL
        CHECK (database_schema_version BETWEEN 1 AND 4294967295),
    database_schema_fingerprint BLOB NOT NULL
        CHECK (length(database_schema_fingerprint) = 32)
) STRICT;

CREATE TRIGGER database_metadata_no_reinsert
BEFORE INSERT ON database_metadata
WHEN EXISTS (SELECT 1 FROM database_metadata)
BEGIN
    SELECT RAISE(ABORT, 'database_metadata is immutable');
END;

CREATE TRIGGER database_metadata_no_update
BEFORE UPDATE ON database_metadata
BEGIN
    SELECT RAISE(ABORT, 'database_metadata is immutable');
END;

CREATE TRIGGER database_metadata_no_delete
BEFORE DELETE ON database_metadata
BEGIN
    SELECT RAISE(ABORT, 'database_metadata is immutable');
END;

CREATE TABLE receiver_instances (
    instance_ordinal INTEGER PRIMARY KEY,
    receiver_instance_id BLOB NOT NULL UNIQUE
        CHECK (length(receiver_instance_id) = 16),
    linux_boot_id BLOB NOT NULL
        CHECK (length(linux_boot_id) = 16),
    started_at_monotonic_us INTEGER NOT NULL
        CHECK (started_at_monotonic_us >= 0),
    clean_stopped_at_monotonic_us INTEGER,
    clean_stop_state_generation INTEGER
        CHECK (
            clean_stop_state_generation IS NULL
            OR clean_stop_state_generation >= 0
        ),
    CHECK (
        (clean_stopped_at_monotonic_us IS NULL
         AND clean_stop_state_generation IS NULL)
        OR
        (clean_stopped_at_monotonic_us IS NOT NULL
         AND clean_stop_state_generation IS NOT NULL
         AND clean_stopped_at_monotonic_us >= started_at_monotonic_us)
    )
) STRICT;

CREATE TRIGGER receiver_instances_start_open
BEFORE INSERT ON receiver_instances
WHEN NEW.clean_stopped_at_monotonic_us IS NOT NULL
     OR NEW.clean_stop_state_generation IS NOT NULL
BEGIN
    SELECT RAISE(ABORT, 'receiver_instances must start without a clean-stop marker');
END;

CREATE TRIGGER receiver_instances_controlled_update
BEFORE UPDATE ON receiver_instances
WHEN NOT (
    OLD.clean_stopped_at_monotonic_us IS NULL
    AND OLD.clean_stop_state_generation IS NULL
    AND NEW.instance_ordinal IS OLD.instance_ordinal
    AND NEW.receiver_instance_id IS OLD.receiver_instance_id
    AND NEW.linux_boot_id IS OLD.linux_boot_id
    AND NEW.started_at_monotonic_us IS OLD.started_at_monotonic_us
    AND NEW.clean_stopped_at_monotonic_us IS NOT NULL
    AND NEW.clean_stop_state_generation IS NOT NULL
)
BEGIN
    SELECT RAISE(ABORT, 'receiver_instances permits only one complete clean-stop transition');
END;

CREATE TRIGGER receiver_instances_no_delete
BEFORE DELETE ON receiver_instances
BEGIN
    SELECT RAISE(ABORT, 'receiver_instances is append-only');
END;

CREATE TABLE quarantined_communicator_states (
    quarantined_state_id INTEGER PRIMARY KEY,
    observed_singleton_id ANY,
    observed_state_format_version ANY,
    observed_generation ANY,
    observed_state_blob ANY,
    observed_state_sha256 ANY,
    calculated_blob_sha256 BLOB
        CHECK (
            calculated_blob_sha256 IS NULL
            OR length(calculated_blob_sha256) = 32
        ),
    preserved_by_receiver_instance_id BLOB NOT NULL
        REFERENCES receiver_instances(receiver_instance_id)
        CHECK (length(preserved_by_receiver_instance_id) = 16),
    preserved_at_monotonic_us INTEGER NOT NULL
        CHECK (preserved_at_monotonic_us >= 0),
    database_schema_version INTEGER NOT NULL
        CHECK (database_schema_version > 0)
) STRICT;

CREATE TRIGGER quarantined_communicator_states_no_update
BEFORE UPDATE ON quarantined_communicator_states
BEGIN
    SELECT RAISE(ABORT, 'quarantined_communicator_states is append-only');
END;

CREATE TRIGGER quarantined_communicator_states_no_delete
BEFORE DELETE ON quarantined_communicator_states
BEGIN
    SELECT RAISE(ABORT, 'quarantined_communicator_states is append-only');
END;

-- Generated receiver enum catalogues.

CREATE TABLE system_time_quality_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO system_time_quality_codes (id, code) VALUES
    (0, 'UNTRUSTED'),
    (1, 'RTC_HOLDOVER'),
    (2, 'NETWORK_SYNCED');

CREATE TRIGGER system_time_quality_codes_no_insert
BEFORE INSERT ON system_time_quality_codes
BEGIN
    SELECT RAISE(ABORT, 'system_time_quality_codes is immutable');
END;

CREATE TRIGGER system_time_quality_codes_no_update
BEFORE UPDATE ON system_time_quality_codes
BEGIN
    SELECT RAISE(ABORT, 'system_time_quality_codes is immutable');
END;

CREATE TRIGGER system_time_quality_codes_no_delete
BEFORE DELETE ON system_time_quality_codes
BEGIN
    SELECT RAISE(ABORT, 'system_time_quality_codes is immutable');
END;

CREATE TABLE rtc_health_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO rtc_health_codes (id, code) VALUES
    (1, 'PRESENT'),
    (2, 'MISSING'),
    (3, 'INVALID');

CREATE TRIGGER rtc_health_codes_no_insert
BEFORE INSERT ON rtc_health_codes
BEGIN
    SELECT RAISE(ABORT, 'rtc_health_codes is immutable');
END;

CREATE TRIGGER rtc_health_codes_no_update
BEFORE UPDATE ON rtc_health_codes
BEGIN
    SELECT RAISE(ABORT, 'rtc_health_codes is immutable');
END;

CREATE TRIGGER rtc_health_codes_no_delete
BEFORE DELETE ON rtc_health_codes
BEGIN
    SELECT RAISE(ABORT, 'rtc_health_codes is immutable');
END;

CREATE TABLE radio_state_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO radio_state_codes (id, code) VALUES
    (1, 'INITIALIZING'),
    (2, 'RX_SINGLE'),
    (3, 'RX_EVENT_PENDING'),
    (4, 'TX_ACTIVE'),
    (5, 'RECOVERING'),
    (6, 'SHUTDOWN'),
    (7, 'INITIALIZATION_FAILED'),
    (8, 'RECOVERY_EXHAUSTED'),
    (9, 'HARDWARE_MISSING');

CREATE TRIGGER radio_state_codes_no_insert
BEFORE INSERT ON radio_state_codes
BEGIN
    SELECT RAISE(ABORT, 'radio_state_codes is immutable');
END;

CREATE TRIGGER radio_state_codes_no_update
BEFORE UPDATE ON radio_state_codes
BEGIN
    SELECT RAISE(ABORT, 'radio_state_codes is immutable');
END;

CREATE TRIGGER radio_state_codes_no_delete
BEFORE DELETE ON radio_state_codes
BEGIN
    SELECT RAISE(ABORT, 'radio_state_codes is immutable');
END;

CREATE TABLE persistence_admission_state_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO persistence_admission_state_codes (id, code) VALUES
    (0, 'UNAVAILABLE_STARTING'),
    (1, 'AVAILABLE'),
    (2, 'UNAVAILABLE_LOW_SPACE'),
    (3, 'UNAVAILABLE_DISK_FULL'),
    (4, 'UNAVAILABLE_CORRUPT'),
    (5, 'UNAVAILABLE_IO'),
    (6, 'UNAVAILABLE_INCOMPATIBLE_SCHEMA');

CREATE TRIGGER persistence_admission_state_codes_no_insert
BEFORE INSERT ON persistence_admission_state_codes
BEGIN
    SELECT RAISE(ABORT, 'persistence_admission_state_codes is immutable');
END;

CREATE TRIGGER persistence_admission_state_codes_no_update
BEFORE UPDATE ON persistence_admission_state_codes
BEGIN
    SELECT RAISE(ABORT, 'persistence_admission_state_codes is immutable');
END;

CREATE TRIGGER persistence_admission_state_codes_no_delete
BEFORE DELETE ON persistence_admission_state_codes
BEGIN
    SELECT RAISE(ABORT, 'persistence_admission_state_codes is immutable');
END;

CREATE TABLE persist_queue_entity_kind_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO persist_queue_entity_kind_codes (id, code) VALUES
    (1, 'MEASUREMENT_PROFILE'),
    (2, 'PROFILE_ONLY'),
    (3, 'RECEIVER_HEALTH_REQUEST'),
    (4, 'DIAGNOSTIC'),
    (5, 'CLOCK_OBSERVATION');

CREATE TRIGGER persist_queue_entity_kind_codes_no_insert
BEFORE INSERT ON persist_queue_entity_kind_codes
BEGIN
    SELECT RAISE(ABORT, 'persist_queue_entity_kind_codes is immutable');
END;

CREATE TRIGGER persist_queue_entity_kind_codes_no_update
BEFORE UPDATE ON persist_queue_entity_kind_codes
BEGIN
    SELECT RAISE(ABORT, 'persist_queue_entity_kind_codes is immutable');
END;

CREATE TRIGGER persist_queue_entity_kind_codes_no_delete
BEFORE DELETE ON persist_queue_entity_kind_codes
BEGIN
    SELECT RAISE(ABORT, 'persist_queue_entity_kind_codes is immutable');
END;

CREATE TABLE processing_result_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO processing_result_codes (id, code) VALUES
    (1, 'RADIO_ERROR'),
    (2, 'UNKNOWN_NODE'),
    (3, 'AUTHENTICATION_FAILED'),
    (4, 'WRONG_DIRECTION'),
    (5, 'REJECTED_UNSUPPORTED_CONTROL'),
    (6, 'REJECTED_UNSUPPORTED_DOMAIN'),
    (7, 'REJECTED_MALFORMED_LENGTH'),
    (8, 'REJECTED_MALFORMED_BODY'),
    (9, 'RETRY_LATER_QUEUE_FULL'),
    (10, 'RETRY_LATER_PERSISTENCE_UNAVAILABLE'),
    (11, 'ACCEPTED');

CREATE TRIGGER processing_result_codes_no_insert
BEFORE INSERT ON processing_result_codes
BEGIN
    SELECT RAISE(ABORT, 'processing_result_codes is immutable');
END;

CREATE TRIGGER processing_result_codes_no_update
BEFORE UPDATE ON processing_result_codes
BEGIN
    SELECT RAISE(ABORT, 'processing_result_codes is immutable');
END;

CREATE TRIGGER processing_result_codes_no_delete
BEFORE DELETE ON processing_result_codes
BEGIN
    SELECT RAISE(ABORT, 'processing_result_codes is immutable');
END;

CREATE TABLE ack_selection_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO ack_selection_codes (id, code) VALUES
    (0, 'NONE'),
    (3, 'ACCEPTED'),
    (4, 'RETRY_LATER'),
    (5, 'REJECTED_UNSUPPORTED'),
    (6, 'REJECTED_MALFORMED');

CREATE TRIGGER ack_selection_codes_no_insert
BEFORE INSERT ON ack_selection_codes
BEGIN
    SELECT RAISE(ABORT, 'ack_selection_codes is immutable');
END;

CREATE TRIGGER ack_selection_codes_no_update
BEFORE UPDATE ON ack_selection_codes
BEGIN
    SELECT RAISE(ABORT, 'ack_selection_codes is immutable');
END;

CREATE TRIGGER ack_selection_codes_no_delete
BEFORE DELETE ON ack_selection_codes
BEGIN
    SELECT RAISE(ABORT, 'ack_selection_codes is immutable');
END;

CREATE TABLE ack_tx_result_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO ack_tx_result_codes (id, code) VALUES
    (1, 'NOT_APPLICABLE'),
    (2, 'SUPPRESSED_AIRTIME_BUDGET'),
    (3, 'SET_TX_FAILED'),
    (4, 'TX_TIMEOUT'),
    (5, 'TX_DONE'),
    (6, 'UNKNOWN_INTERRUPTED');

CREATE TRIGGER ack_tx_result_codes_no_insert
BEFORE INSERT ON ack_tx_result_codes
BEGIN
    SELECT RAISE(ABORT, 'ack_tx_result_codes is immutable');
END;

CREATE TRIGGER ack_tx_result_codes_no_update
BEFORE UPDATE ON ack_tx_result_codes
BEGIN
    SELECT RAISE(ABORT, 'ack_tx_result_codes is immutable');
END;

CREATE TRIGGER ack_tx_result_codes_no_delete
BEFORE DELETE ON ack_tx_result_codes
BEGIN
    SELECT RAISE(ABORT, 'ack_tx_result_codes is immutable');
END;

CREATE TABLE persistence_classification_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO persistence_classification_codes (id, code) VALUES
    (0, 'NOT_APPLICABLE'),
    (1, 'FIRST_SEEN'),
    (2, 'RETRANSMISSION'),
    (3, 'DUPLICATE_SAME_CONTENT'),
    (4, 'DUPLICATE_CONFLICT'),
    (5, 'MESSAGE_ID_CONFLICT');

CREATE TRIGGER persistence_classification_codes_no_insert
BEFORE INSERT ON persistence_classification_codes
BEGIN
    SELECT RAISE(ABORT, 'persistence_classification_codes is immutable');
END;

CREATE TRIGGER persistence_classification_codes_no_update
BEFORE UPDATE ON persistence_classification_codes
BEGIN
    SELECT RAISE(ABORT, 'persistence_classification_codes is immutable');
END;

CREATE TRIGGER persistence_classification_codes_no_delete
BEFORE DELETE ON persistence_classification_codes
BEGIN
    SELECT RAISE(ABORT, 'persistence_classification_codes is immutable');
END;

CREATE TABLE quarantine_failure_reason_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO quarantine_failure_reason_codes (id, code) VALUES
    (1, 'UNSUPPORTED_ENTITY_SCHEMA'),
    (2, 'ENTITY_DECODING_INVARIANT'),
    (3, 'SQL_BINDING_INVARIANT'),
    (4, 'SQL_RANGE_VIOLATION'),
    (5, 'UNEXPECTED_SQL_CONSTRAINT'),
    (6, 'PERSISTENCE_DERIVATION_INVARIANT');

CREATE TRIGGER quarantine_failure_reason_codes_no_insert
BEFORE INSERT ON quarantine_failure_reason_codes
BEGIN
    SELECT RAISE(ABORT, 'quarantine_failure_reason_codes is immutable');
END;

CREATE TRIGGER quarantine_failure_reason_codes_no_update
BEFORE UPDATE ON quarantine_failure_reason_codes
BEGIN
    SELECT RAISE(ABORT, 'quarantine_failure_reason_codes is immutable');
END;

CREATE TRIGGER quarantine_failure_reason_codes_no_delete
BEFORE DELETE ON quarantine_failure_reason_codes
BEGIN
    SELECT RAISE(ABORT, 'quarantine_failure_reason_codes is immutable');
END;

CREATE TABLE diagnostic_severity_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO diagnostic_severity_codes (id, code) VALUES
    (1, 'WARN'),
    (2, 'ERROR'),
    (3, 'FATAL');

CREATE TRIGGER diagnostic_severity_codes_no_insert
BEFORE INSERT ON diagnostic_severity_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_severity_codes is immutable');
END;

CREATE TRIGGER diagnostic_severity_codes_no_update
BEFORE UPDATE ON diagnostic_severity_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_severity_codes is immutable');
END;

CREATE TRIGGER diagnostic_severity_codes_no_delete
BEFORE DELETE ON diagnostic_severity_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_severity_codes is immutable');
END;

CREATE TABLE diagnostic_error_domain_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO diagnostic_error_domain_codes (id, code) VALUES
    (0, 'NONE'),
    (1, 'RADIO'),
    (2, 'TIME'),
    (3, 'PERSISTENCE_CONTROL'),
    (4, 'CORE');

CREATE TRIGGER diagnostic_error_domain_codes_no_insert
BEFORE INSERT ON diagnostic_error_domain_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_error_domain_codes is immutable');
END;

CREATE TRIGGER diagnostic_error_domain_codes_no_update
BEFORE UPDATE ON diagnostic_error_domain_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_error_domain_codes is immutable');
END;

CREATE TRIGGER diagnostic_error_domain_codes_no_delete
BEFORE DELETE ON diagnostic_error_domain_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_error_domain_codes is immutable');
END;

CREATE TABLE diagnostic_operation_codes (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
) STRICT;

INSERT INTO diagnostic_operation_codes (id, code) VALUES
    (0, 'NONE'),
    (1, 'INITIALIZE'),
    (2, 'VALIDATE'),
    (3, 'READ'),
    (4, 'WRITE'),
    (5, 'APPEND'),
    (6, 'SYNC'),
    (7, 'RECOVER'),
    (8, 'ENCODE'),
    (9, 'DECODE'),
    (10, 'TRANSMIT'),
    (11, 'RECEIVE'),
    (12, 'CLEANUP');

CREATE TRIGGER diagnostic_operation_codes_no_insert
BEFORE INSERT ON diagnostic_operation_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_operation_codes is immutable');
END;

CREATE TRIGGER diagnostic_operation_codes_no_update
BEFORE UPDATE ON diagnostic_operation_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_operation_codes is immutable');
END;

CREATE TRIGGER diagnostic_operation_codes_no_delete
BEFORE DELETE ON diagnostic_operation_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_operation_codes is immutable');
END;

CREATE TABLE diagnostic_error_codes (
    error_domain_id INTEGER NOT NULL
        REFERENCES diagnostic_error_domain_codes(id),
    id INTEGER NOT NULL,
    code TEXT NOT NULL,
    PRIMARY KEY (error_domain_id, id),
    UNIQUE (error_domain_id, code)
) STRICT, WITHOUT ROWID;

INSERT INTO diagnostic_error_codes (error_domain_id, id, code) VALUES
    (1, 0, 'NONE'),
    (1, 1, 'INVALID_ARGUMENT'),
    (1, 2, 'INVALID_STATE'),
    (1, 3, 'IO'),
    (1, 4, 'BUSY_TIMEOUT'),
    (1, 5, 'COMMAND_STATUS'),
    (1, 6, 'DEADLINE'),
    (1, 7, 'UNEXPECTED_IRQ'),
    (1, 8, 'DEVICE_ERROR'),
    (1, 9, 'MALFORMED_RESPONSE'),
    (2, 0, 'NONE'),
    (2, 1, 'IO'),
    (2, 2, 'DEADLINE'),
    (2, 3, 'INVALID_RESPONSE'),
    (2, 4, 'COMMAND_REJECTED'),
    (2, 5, 'OUTCOME_UNKNOWN'),
    (2, 6, 'CLOCK_INTERFERENCE'),
    (2, 7, 'RTC_READBACK_MISMATCH'),
    (2, 8, 'CALCULATION_RANGE'),
    (3, 0, 'NONE'),
    (3, 1, 'CONFIGURATION_REJECTED'),
    (3, 2, 'HOST_IDENTITY_REJECTED'),
    (3, 3, 'STATE_MISSING'),
    (3, 4, 'STATE_CORRUPT'),
    (3, 5, 'UNSUPPORTED_STATE_VERSION'),
    (3, 6, 'STATE_POLICY_MISMATCH'),
    (3, 7, 'IO'),
    (3, 8, 'DATABASE'),
    (3, 9, 'DEADLINE'),
    (3, 10, 'CHANNEL_CLOSED'),
    (4, 0, 'NONE'),
    (4, 1, 'INVALID_ARGUMENT'),
    (4, 2, 'INVALID_STATE'),
    (4, 3, 'REPRESENTATION_INVARIANT'),
    (4, 4, 'PERSIST_QUEUE_CONTRACT'),
    (4, 5, 'PERSISTENCE_CONTROL_CONTRACT'),
    (4, 6, 'MEMORY_EXHAUSTED'),
    (4, 7, 'CODEC_BACKEND'),
    (4, 8, 'CRYPTO_BACKEND'),
    (4, 9, 'ARITHMETIC_RANGE'),
    (4, 10, 'UNEXPECTED_EXCEPTION');

CREATE TRIGGER diagnostic_error_codes_no_insert
BEFORE INSERT ON diagnostic_error_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_error_codes is immutable');
END;

CREATE TRIGGER diagnostic_error_codes_no_update
BEFORE UPDATE ON diagnostic_error_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_error_codes is immutable');
END;

CREATE TRIGGER diagnostic_error_codes_no_delete
BEFORE DELETE ON diagnostic_error_codes
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_error_codes is immutable');
END;

CREATE TABLE diagnostic_context_schemas (
    error_domain_id INTEGER NOT NULL
        REFERENCES diagnostic_error_domain_codes(id),
    id INTEGER NOT NULL,
    code TEXT NOT NULL,
    PRIMARY KEY (error_domain_id, id),
    UNIQUE (error_domain_id, code)
) STRICT, WITHOUT ROWID;

INSERT INTO diagnostic_context_schemas (error_domain_id, id, code) VALUES
    (1, 0, 'NONE'),
    (1, 1, 'RECEIVER_RADIO_EPISODE_CONTEXT_V1'),
    (2, 0, 'NONE'),
    (2, 1, 'RECEIVER_TIME_EPISODE_CONTEXT_V1'),
    (3, 0, 'NONE'),
    (3, 1, 'RECEIVER_PERSISTENCE_CONTROL_CONTEXT_V1'),
    (4, 0, 'NONE'),
    (4, 1, 'RECEIVER_CORE_FAILURE_CONTEXT_V1');

CREATE TRIGGER diagnostic_context_schemas_no_insert
BEFORE INSERT ON diagnostic_context_schemas
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_context_schemas is immutable');
END;

CREATE TRIGGER diagnostic_context_schemas_no_update
BEFORE UPDATE ON diagnostic_context_schemas
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_context_schemas is immutable');
END;

CREATE TRIGGER diagnostic_context_schemas_no_delete
BEFORE DELETE ON diagnostic_context_schemas
BEGIN
    SELECT RAISE(ABORT, 'diagnostic_context_schemas is immutable');
END;

-- Generated receiver entity tables.

CREATE TABLE clock_observations (
    receiver_instance_id BLOB NOT NULL CHECK (length(receiver_instance_id) = 16),
    observation_sequence INTEGER NOT NULL CHECK (observation_sequence BETWEEN 0 AND 9223372036854775807),
    clock_state_generation INTEGER NOT NULL CHECK (clock_state_generation BETWEEN 0 AND 9223372036854775807),
    sampled_at_monotonic_us INTEGER NOT NULL CHECK (sampled_at_monotonic_us BETWEEN 0 AND 9223372036854775807),
    sampled_at_utc_us INTEGER CHECK (sampled_at_utc_us IS NULL OR sampled_at_utc_us BETWEEN -9223372036854775808 AND 9223372036854775807),
    step_discontinuity_boundary INTEGER NOT NULL CHECK (step_discontinuity_boundary IN (0, 1)),
    system_time_quality_id INTEGER NOT NULL,
    rtc_health_id INTEGER NOT NULL,
    PRIMARY KEY (receiver_instance_id, observation_sequence),
    FOREIGN KEY (receiver_instance_id) REFERENCES receiver_instances(receiver_instance_id),
    FOREIGN KEY (system_time_quality_id) REFERENCES system_time_quality_codes(id),
    FOREIGN KEY (rtc_health_id) REFERENCES rtc_health_codes(id)
) STRICT, WITHOUT ROWID;

CREATE TRIGGER clock_observations_no_update
BEFORE UPDATE ON clock_observations
BEGIN
    SELECT RAISE(ABORT, 'clock_observations is append-only');
END;

CREATE TRIGGER clock_observations_no_delete
BEFORE DELETE ON clock_observations
BEGIN
    SELECT RAISE(ABORT, 'clock_observations is append-only');
END;

CREATE TABLE diagnostics (
    receiver_instance_id BLOB NOT NULL CHECK (length(receiver_instance_id) = 16),
    diagnostic_sequence INTEGER NOT NULL CHECK (diagnostic_sequence BETWEEN 0 AND 9223372036854775807),
    sampled_at_monotonic_us INTEGER NOT NULL CHECK (sampled_at_monotonic_us BETWEEN 0 AND 9223372036854775807),
    severity_id INTEGER NOT NULL,
    error_domain_id INTEGER NOT NULL,
    operation_id INTEGER NOT NULL,
    error_code_id INTEGER NOT NULL CHECK (error_code_id BETWEEN 0 AND 65535),
    context_schema_id INTEGER NOT NULL CHECK (context_schema_id BETWEEN 0 AND 255),
    context_length INTEGER NOT NULL CHECK (context_length BETWEEN 0 AND 128),
    context BLOB NOT NULL CHECK (length(context) = 128),
    PRIMARY KEY (receiver_instance_id, diagnostic_sequence),
    FOREIGN KEY (receiver_instance_id) REFERENCES receiver_instances(receiver_instance_id),
    FOREIGN KEY (severity_id) REFERENCES diagnostic_severity_codes(id),
    FOREIGN KEY (error_domain_id) REFERENCES diagnostic_error_domain_codes(id),
    FOREIGN KEY (operation_id) REFERENCES diagnostic_operation_codes(id),
    FOREIGN KEY (error_domain_id, error_code_id) REFERENCES diagnostic_error_codes(error_domain_id, id),
    FOREIGN KEY (error_domain_id, context_schema_id) REFERENCES diagnostic_context_schemas(error_domain_id, id)
) STRICT, WITHOUT ROWID;

CREATE TRIGGER diagnostics_no_update
BEFORE UPDATE ON diagnostics
BEGIN
    SELECT RAISE(ABORT, 'diagnostics is append-only');
END;

CREATE TRIGGER diagnostics_no_delete
BEFORE DELETE ON diagnostics
BEGIN
    SELECT RAISE(ABORT, 'diagnostics is append-only');
END;

CREATE TABLE quarantined_entities (
    quarantine_id BLOB NOT NULL CHECK (length(quarantine_id) = 32),
    entity_kind_id INTEGER NOT NULL,
    entity_schema_version INTEGER NOT NULL CHECK (entity_schema_version BETWEEN 0 AND 255),
    entity_length INTEGER NOT NULL CHECK (entity_length BETWEEN 2 AND 490),
    entity_bytes BLOB NOT NULL CHECK (length(entity_bytes) BETWEEN 2 AND 490),
    receiver_instance_id BLOB NOT NULL CHECK (length(receiver_instance_id) = 16),
    quarantined_at_monotonic_us INTEGER NOT NULL CHECK (quarantined_at_monotonic_us BETWEEN 0 AND 9223372036854775807),
    database_schema_version INTEGER NOT NULL CHECK (database_schema_version BETWEEN 1 AND 4294967295),
    failure_reason_id INTEGER NOT NULL,
    failure_operation_id INTEGER NOT NULL,
    sqlite_primary_code INTEGER CHECK (sqlite_primary_code IS NULL OR sqlite_primary_code BETWEEN -2147483648 AND 2147483647),
    sqlite_extended_code INTEGER CHECK (sqlite_extended_code IS NULL OR sqlite_extended_code BETWEEN -2147483648 AND 2147483647),
    os_errno INTEGER CHECK (os_errno IS NULL OR os_errno BETWEEN -2147483648 AND 2147483647),
    isolation_attempt_count INTEGER NOT NULL CHECK (isolation_attempt_count BETWEEN 1 AND 4294967295),
    CHECK (length(entity_bytes) = entity_length),
    PRIMARY KEY (quarantine_id),
    FOREIGN KEY (entity_kind_id) REFERENCES persist_queue_entity_kind_codes(id),
    FOREIGN KEY (receiver_instance_id) REFERENCES receiver_instances(receiver_instance_id),
    FOREIGN KEY (failure_reason_id) REFERENCES quarantine_failure_reason_codes(id),
    FOREIGN KEY (failure_operation_id) REFERENCES diagnostic_operation_codes(id)
) STRICT, WITHOUT ROWID;

CREATE TRIGGER quarantined_entities_no_update
BEFORE UPDATE ON quarantined_entities
BEGIN
    SELECT RAISE(ABORT, 'quarantined_entities is append-only');
END;

CREATE TRIGGER quarantined_entities_no_delete
BEFORE DELETE ON quarantined_entities
BEGIN
    SELECT RAISE(ABORT, 'quarantined_entities is append-only');
END;

CREATE TABLE receiver_health (
    receiver_instance_id BLOB NOT NULL CHECK (length(receiver_instance_id) = 16),
    health_sequence INTEGER NOT NULL CHECK (health_sequence BETWEEN 0 AND 9223372036854775807),
    communicator_sampled_at_monotonic_us INTEGER NOT NULL CHECK (communicator_sampled_at_monotonic_us BETWEEN 0 AND 9223372036854775807),
    radio_state_id INTEGER NOT NULL,
    radio_recovery_attempts INTEGER NOT NULL CHECK (radio_recovery_attempts BETWEEN 0 AND 9223372036854775807),
    radio_recovery_successes INTEGER NOT NULL CHECK (radio_recovery_successes BETWEEN 0 AND 9223372036854775807),
    radio_recovery_failures INTEGER NOT NULL CHECK (radio_recovery_failures BETWEEN 0 AND 9223372036854775807),
    radio_recovery_attempts_by_reason_busy_timeout INTEGER NOT NULL CHECK (radio_recovery_attempts_by_reason_busy_timeout BETWEEN 0 AND 9223372036854775807),
    radio_recovery_attempts_by_reason_spi_failure INTEGER NOT NULL CHECK (radio_recovery_attempts_by_reason_spi_failure BETWEEN 0 AND 9223372036854775807),
    radio_recovery_attempts_by_reason_unexpected_irq INTEGER NOT NULL CHECK (radio_recovery_attempts_by_reason_unexpected_irq BETWEEN 0 AND 9223372036854775807),
    radio_recovery_attempts_by_reason_tx_outcome_uncertain INTEGER NOT NULL CHECK (radio_recovery_attempts_by_reason_tx_outcome_uncertain BETWEEN 0 AND 9223372036854775807),
    radio_recovery_attempts_by_reason_rx_profile_restore_failed INTEGER NOT NULL CHECK (radio_recovery_attempts_by_reason_rx_profile_restore_failed BETWEEN 0 AND 9223372036854775807),
    radio_recovery_attempts_by_reason_set_rx_failed INTEGER NOT NULL CHECK (radio_recovery_attempts_by_reason_set_rx_failed BETWEEN 0 AND 9223372036854775807),
    radio_recovery_attempts_by_reason_status_unconfirmed INTEGER NOT NULL CHECK (radio_recovery_attempts_by_reason_status_unconfirmed BETWEEN 0 AND 9223372036854775807),
    radio_recovery_attempts_by_reason_hardware_unreachable INTEGER NOT NULL CHECK (radio_recovery_attempts_by_reason_hardware_unreachable BETWEEN 0 AND 9223372036854775807),
    system_time_quality_id INTEGER NOT NULL,
    rtc_health_id INTEGER NOT NULL,
    time_quality_transition_count INTEGER NOT NULL CHECK (time_quality_transition_count BETWEEN 0 AND 9223372036854775807),
    rtc_health_transition_count INTEGER NOT NULL CHECK (rtc_health_transition_count BETWEEN 0 AND 9223372036854775807),
    last_time_quality_transition_monotonic_us INTEGER CHECK (last_time_quality_transition_monotonic_us IS NULL OR last_time_quality_transition_monotonic_us BETWEEN 0 AND 9223372036854775807),
    last_rtc_health_transition_monotonic_us INTEGER CHECK (last_rtc_health_transition_monotonic_us IS NULL OR last_rtc_health_transition_monotonic_us BETWEEN 0 AND 9223372036854775807),
    chrony_step_command_results_submitted INTEGER NOT NULL CHECK (chrony_step_command_results_submitted BETWEEN 0 AND 9223372036854775807),
    chrony_step_command_results_not_submitted INTEGER NOT NULL CHECK (chrony_step_command_results_not_submitted BETWEEN 0 AND 9223372036854775807),
    chrony_step_command_results_outcome_unknown INTEGER NOT NULL CHECK (chrony_step_command_results_outcome_unknown BETWEEN 0 AND 9223372036854775807),
    rtc_write_results_completed INTEGER NOT NULL CHECK (rtc_write_results_completed BETWEEN 0 AND 9223372036854775807),
    rtc_write_results_not_applied INTEGER NOT NULL CHECK (rtc_write_results_not_applied BETWEEN 0 AND 9223372036854775807),
    rtc_write_results_outcome_unknown INTEGER NOT NULL CHECK (rtc_write_results_outcome_unknown BETWEEN 0 AND 9223372036854775807),
    rtc_write_readback_verified_count INTEGER NOT NULL CHECK (rtc_write_readback_verified_count BETWEEN 0 AND 9223372036854775807),
    rtc_write_trust_invalidated_count INTEGER NOT NULL CHECK (rtc_write_trust_invalidated_count BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_measurement_profile_reserved INTEGER NOT NULL CHECK (persist_queue_admission_counts_measurement_profile_reserved BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_measurement_profile_persistence_unavailable INTEGER NOT NULL CHECK (persist_queue_admission_counts_measurement_profile_persistence_unavailable BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_measurement_profile_queue_full INTEGER NOT NULL CHECK (persist_queue_admission_counts_measurement_profile_queue_full BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_profile_only_reserved INTEGER NOT NULL CHECK (persist_queue_admission_counts_profile_only_reserved BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_profile_only_persistence_unavailable INTEGER NOT NULL CHECK (persist_queue_admission_counts_profile_only_persistence_unavailable BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_profile_only_queue_full INTEGER NOT NULL CHECK (persist_queue_admission_counts_profile_only_queue_full BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_receiver_health_request_reserved INTEGER NOT NULL CHECK (persist_queue_admission_counts_receiver_health_request_reserved BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_receiver_health_request_persistence_unavailable INTEGER NOT NULL CHECK (persist_queue_admission_counts_receiver_health_request_persistence_unavailable BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_receiver_health_request_queue_full INTEGER NOT NULL CHECK (persist_queue_admission_counts_receiver_health_request_queue_full BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_diagnostic_reserved INTEGER NOT NULL CHECK (persist_queue_admission_counts_diagnostic_reserved BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_diagnostic_persistence_unavailable INTEGER NOT NULL CHECK (persist_queue_admission_counts_diagnostic_persistence_unavailable BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_diagnostic_queue_full INTEGER NOT NULL CHECK (persist_queue_admission_counts_diagnostic_queue_full BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_clock_observation_reserved INTEGER NOT NULL CHECK (persist_queue_admission_counts_clock_observation_reserved BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_clock_observation_persistence_unavailable INTEGER NOT NULL CHECK (persist_queue_admission_counts_clock_observation_persistence_unavailable BETWEEN 0 AND 9223372036854775807),
    persist_queue_admission_counts_clock_observation_queue_full INTEGER NOT NULL CHECK (persist_queue_admission_counts_clock_observation_queue_full BETWEEN 0 AND 9223372036854775807),
    persistence_sampled_at_monotonic_us INTEGER NOT NULL CHECK (persistence_sampled_at_monotonic_us BETWEEN 0 AND 9223372036854775807),
    persistence_admission_generation INTEGER NOT NULL CHECK (persistence_admission_generation BETWEEN 0 AND 9223372036854775807),
    persistence_admission_state_id INTEGER NOT NULL,
    persistence_admission_changed_at_monotonic_us INTEGER NOT NULL CHECK (persistence_admission_changed_at_monotonic_us BETWEEN 0 AND 9223372036854775807),
    persistence_admission_transition_counts_unavailable_starting INTEGER NOT NULL CHECK (persistence_admission_transition_counts_unavailable_starting BETWEEN 0 AND 9223372036854775807),
    persistence_admission_transition_counts_available INTEGER NOT NULL CHECK (persistence_admission_transition_counts_available BETWEEN 0 AND 9223372036854775807),
    persistence_admission_transition_counts_unavailable_low_space INTEGER NOT NULL CHECK (persistence_admission_transition_counts_unavailable_low_space BETWEEN 0 AND 9223372036854775807),
    persistence_admission_transition_counts_unavailable_disk_full INTEGER NOT NULL CHECK (persistence_admission_transition_counts_unavailable_disk_full BETWEEN 0 AND 9223372036854775807),
    persistence_admission_transition_counts_unavailable_corrupt INTEGER NOT NULL CHECK (persistence_admission_transition_counts_unavailable_corrupt BETWEEN 0 AND 9223372036854775807),
    persistence_admission_transition_counts_unavailable_io INTEGER NOT NULL CHECK (persistence_admission_transition_counts_unavailable_io BETWEEN 0 AND 9223372036854775807),
    persistence_admission_transition_counts_unavailable_incompatible_schema INTEGER NOT NULL CHECK (persistence_admission_transition_counts_unavailable_incompatible_schema BETWEEN 0 AND 9223372036854775807),
    durable_quarantine_successes INTEGER NOT NULL CHECK (durable_quarantine_successes BETWEEN 0 AND 9223372036854775807),
    durable_quarantine_failures INTEGER NOT NULL CHECK (durable_quarantine_failures BETWEEN 0 AND 9223372036854775807),
    batch_transaction_attempts INTEGER NOT NULL CHECK (batch_transaction_attempts BETWEEN 0 AND 9223372036854775807),
    batch_transaction_commits INTEGER NOT NULL CHECK (batch_transaction_commits BETWEEN 0 AND 9223372036854775807),
    batch_transaction_failures INTEGER NOT NULL CHECK (batch_transaction_failures BETWEEN 0 AND 9223372036854775807),
    batch_entities_committed INTEGER NOT NULL CHECK (batch_entities_committed BETWEEN 0 AND 9223372036854775807),
    batch_encoded_bytes_committed INTEGER NOT NULL CHECK (batch_encoded_bytes_committed BETWEEN 0 AND 9223372036854775807),
    batch_commit_duration_total_us INTEGER NOT NULL CHECK (batch_commit_duration_total_us BETWEEN 0 AND 9223372036854775807),
    batch_commit_duration_max_us INTEGER NOT NULL CHECK (batch_commit_duration_max_us BETWEEN 0 AND 9223372036854775807),
    wal_checkpoint_attempts INTEGER NOT NULL CHECK (wal_checkpoint_attempts BETWEEN 0 AND 9223372036854775807),
    wal_checkpoint_successes INTEGER NOT NULL CHECK (wal_checkpoint_successes BETWEEN 0 AND 9223372036854775807),
    wal_checkpoint_failures INTEGER NOT NULL CHECK (wal_checkpoint_failures BETWEEN 0 AND 9223372036854775807),
    linux_load_1m_milli INTEGER CHECK (linux_load_1m_milli IS NULL OR linux_load_1m_milli BETWEEN 0 AND 4294967295),
    cpu_temperature_milli_c INTEGER CHECK (cpu_temperature_milli_c IS NULL OR cpu_temperature_milli_c BETWEEN -2147483648 AND 2147483647),
    memory_available_bytes INTEGER CHECK (memory_available_bytes IS NULL OR memory_available_bytes BETWEEN 0 AND 9223372036854775807),
    sqlite_filesystem_available_bytes INTEGER CHECK (sqlite_filesystem_available_bytes IS NULL OR sqlite_filesystem_available_bytes BETWEEN 0 AND 9223372036854775807),
    sqlite_database_size_bytes INTEGER CHECK (sqlite_database_size_bytes IS NULL OR sqlite_database_size_bytes BETWEEN 0 AND 9223372036854775807),
    sqlite_wal_size_bytes INTEGER CHECK (sqlite_wal_size_bytes IS NULL OR sqlite_wal_size_bytes BETWEEN 0 AND 9223372036854775807),
    ntp_offset_us INTEGER CHECK (ntp_offset_us IS NULL OR ntp_offset_us BETWEEN -9223372036854775808 AND 9223372036854775807),
    PRIMARY KEY (receiver_instance_id, health_sequence),
    FOREIGN KEY (receiver_instance_id) REFERENCES receiver_instances(receiver_instance_id),
    FOREIGN KEY (radio_state_id) REFERENCES radio_state_codes(id),
    FOREIGN KEY (system_time_quality_id) REFERENCES system_time_quality_codes(id),
    FOREIGN KEY (rtc_health_id) REFERENCES rtc_health_codes(id),
    FOREIGN KEY (persistence_admission_state_id) REFERENCES persistence_admission_state_codes(id)
) STRICT, WITHOUT ROWID;

CREATE TRIGGER receiver_health_no_update
BEFORE UPDATE ON receiver_health
BEGIN
    SELECT RAISE(ABORT, 'receiver_health is append-only');
END;

CREATE TRIGGER receiver_health_no_delete
BEFORE DELETE ON receiver_health
BEGIN
    SELECT RAISE(ABORT, 'receiver_health is append-only');
END;

CREATE TABLE message_profiles (
    receiver_instance_id BLOB NOT NULL CHECK (length(receiver_instance_id) = 16),
    occurrence_sequence INTEGER NOT NULL CHECK (occurrence_sequence BETWEEN 0 AND 9223372036854775807),
    received_at_monotonic_us INTEGER NOT NULL CHECK (received_at_monotonic_us BETWEEN 0 AND 9223372036854775807),
    persist_queue_used_bytes_before_admission INTEGER NOT NULL CHECK (persist_queue_used_bytes_before_admission BETWEEN 0 AND 9223372036854775807),
    persist_queue_capacity_bytes INTEGER NOT NULL CHECK (persist_queue_capacity_bytes BETWEEN 0 AND 9223372036854775807),
    received_frame_length INTEGER CHECK (received_frame_length IS NULL OR received_frame_length BETWEEN 0 AND 255),
    received_frame BLOB CHECK (received_frame IS NULL OR length(received_frame) = 255),
    claimed_control INTEGER CHECK (claimed_control IS NULL OR claimed_control BETWEEN 0 AND 255),
    claimed_domain INTEGER CHECK (claimed_domain IS NULL OR claimed_domain BETWEEN 0 AND 255),
    claimed_node_id BLOB CHECK (claimed_node_id IS NULL OR length(claimed_node_id) = 8),
    claimed_message_id INTEGER CHECK (claimed_message_id IS NULL OR claimed_message_id BETWEEN 0 AND 4294967295),
    header_authenticated INTEGER NOT NULL CHECK (header_authenticated IN (0, 1)),
    decoded_sample_id INTEGER CHECK (decoded_sample_id IS NULL OR decoded_sample_id BETWEEN 0 AND 4294967295),
    rssi_dbm_x2 INTEGER CHECK (rssi_dbm_x2 IS NULL OR rssi_dbm_x2 BETWEEN -32768 AND 32767),
    snr_db_x4 INTEGER CHECK (snr_db_x4 IS NULL OR snr_db_x4 BETWEEN -32768 AND 32767),
    irq_status INTEGER CHECK (irq_status IS NULL OR irq_status BETWEEN 0 AND 65535),
    device_errors INTEGER CHECK (device_errors IS NULL OR device_errors BETWEEN 0 AND 65535),
    processing_result_id INTEGER NOT NULL,
    ack_selected_id INTEGER NOT NULL,
    ack_tx_result_id INTEGER NOT NULL,
    ack_frame BLOB CHECK (ack_frame IS NULL OR length(ack_frame) = 23),
    busy_wait_total_us INTEGER NOT NULL CHECK (busy_wait_total_us BETWEEN 0 AND 9223372036854775807),
    busy_wait_max_us INTEGER NOT NULL CHECK (busy_wait_max_us BETWEEN 0 AND 9223372036854775807),
    busy_wait_count INTEGER NOT NULL CHECK (busy_wait_count BETWEEN 0 AND 4294967295),
    busy_timeout_count INTEGER NOT NULL CHECK (busy_timeout_count BETWEEN 0 AND 4294967295),
    last_busy_timeout_opcode INTEGER CHECK (last_busy_timeout_opcode IS NULL OR last_busy_timeout_opcode BETWEEN 0 AND 255),
    t1_handler_started_monotonic_us INTEGER NOT NULL CHECK (t1_handler_started_monotonic_us BETWEEN 0 AND 9223372036854775807),
    t2_packet_copied_monotonic_us INTEGER CHECK (t2_packet_copied_monotonic_us IS NULL OR t2_packet_copied_monotonic_us BETWEEN 0 AND 9223372036854775807),
    t3_authentication_completed_monotonic_us INTEGER CHECK (t3_authentication_completed_monotonic_us IS NULL OR t3_authentication_completed_monotonic_us BETWEEN 0 AND 9223372036854775807),
    t4_set_tx_attempted_monotonic_us INTEGER CHECK (t4_set_tx_attempted_monotonic_us IS NULL OR t4_set_tx_attempted_monotonic_us BETWEEN 0 AND 9223372036854775807),
    t5_tx_done_monotonic_us INTEGER CHECK (t5_tx_done_monotonic_us IS NULL OR t5_tx_done_monotonic_us BETWEEN 0 AND 9223372036854775807),
    t6_set_rx_issued_monotonic_us INTEGER CHECK (t6_set_rx_issued_monotonic_us IS NULL OR t6_set_rx_issued_monotonic_us BETWEEN 0 AND 9223372036854775807),
    persistence_classification_id INTEGER NOT NULL,
    PRIMARY KEY (receiver_instance_id, occurrence_sequence),
    FOREIGN KEY (receiver_instance_id) REFERENCES receiver_instances(receiver_instance_id),
    FOREIGN KEY (processing_result_id) REFERENCES processing_result_codes(id),
    FOREIGN KEY (ack_selected_id) REFERENCES ack_selection_codes(id),
    FOREIGN KEY (ack_tx_result_id) REFERENCES ack_tx_result_codes(id),
    FOREIGN KEY (persistence_classification_id) REFERENCES persistence_classification_codes(id)
) STRICT, WITHOUT ROWID;

CREATE TRIGGER message_profiles_no_update
BEFORE UPDATE ON message_profiles
BEGIN
    SELECT RAISE(ABORT, 'message_profiles is append-only');
END;

CREATE TRIGGER message_profiles_no_delete
BEFORE DELETE ON message_profiles
BEGIN
    SELECT RAISE(ABORT, 'message_profiles is append-only');
END;

CREATE TABLE reading_messages (
    node_id BLOB NOT NULL CHECK (length(node_id) = 8),
    message_id INTEGER NOT NULL CHECK (message_id BETWEEN 0 AND 4294967295),
    sample_id INTEGER NOT NULL CHECK (sample_id BETWEEN 0 AND 4294967295),
    reading_body BLOB NOT NULL CHECK (length(reading_body) = 32),
    is_canonical_for_sample INTEGER NOT NULL CHECK (is_canonical_for_sample IN (0, 1)),
    run_ms INTEGER NOT NULL CHECK (run_ms BETWEEN 0 AND 65535),
    soil_0_mv INTEGER NOT NULL CHECK (soil_0_mv BETWEEN 0 AND 65535),
    soil_1_mv INTEGER NOT NULL CHECK (soil_1_mv BETWEEN 0 AND 65535),
    soil_temp_0_centi_c INTEGER NOT NULL CHECK (soil_temp_0_centi_c BETWEEN -32768 AND 32767),
    soil_temp_1_centi_c INTEGER NOT NULL CHECK (soil_temp_1_centi_c BETWEEN -32768 AND 32767),
    enclosure_centi_c INTEGER NOT NULL CHECK (enclosure_centi_c BETWEEN -32768 AND 32767),
    enclosure_pressure_pa INTEGER NOT NULL CHECK (enclosure_pressure_pa BETWEEN 0 AND 4294967295),
    enclosure_humidity_centi_pct INTEGER NOT NULL CHECK (enclosure_humidity_centi_pct BETWEEN 0 AND 65535),
    reset_reason INTEGER NOT NULL CHECK (reset_reason BETWEEN 0 AND 255),
    previous_current_tx_attempts INTEGER NOT NULL CHECK (previous_current_tx_attempts BETWEEN 0 AND 255),
    previous_awake_ms INTEGER NOT NULL CHECK (previous_awake_ms BETWEEN 0 AND 65535),
    previous_current_delivery_ms INTEGER NOT NULL CHECK (previous_current_delivery_ms BETWEEN 0 AND 65535),
    previous_cycle_tx_attempts INTEGER NOT NULL CHECK (previous_cycle_tx_attempts BETWEEN 0 AND 255),
    previous_cycle_accepted_readings INTEGER NOT NULL CHECK (previous_cycle_accepted_readings BETWEEN 0 AND 255),
    flags INTEGER NOT NULL CHECK (flags BETWEEN 0 AND 65535),
    first_receiver_instance_id BLOB NOT NULL CHECK (length(first_receiver_instance_id) = 16),
    first_occurrence_sequence INTEGER NOT NULL CHECK (first_occurrence_sequence BETWEEN 0 AND 9223372036854775807),
    PRIMARY KEY (node_id, message_id),
    FOREIGN KEY (first_receiver_instance_id, first_occurrence_sequence) REFERENCES message_profiles(receiver_instance_id, occurrence_sequence)
) STRICT, WITHOUT ROWID;

CREATE UNIQUE INDEX reading_messages_one_canonical_sample
ON reading_messages (node_id, sample_id)
WHERE is_canonical_for_sample = 1;

CREATE TRIGGER reading_messages_no_update
BEFORE UPDATE ON reading_messages
BEGIN
    SELECT RAISE(ABORT, 'reading_messages is append-only');
END;

CREATE TRIGGER reading_messages_no_delete
BEFORE DELETE ON reading_messages
BEGIN
    SELECT RAISE(ABORT, 'reading_messages is append-only');
END;

CREATE TABLE communicator_state (
    singleton_id INTEGER NOT NULL CHECK (singleton_id = 1),
    state_format_version INTEGER NOT NULL CHECK (state_format_version = 1),
    generation INTEGER NOT NULL CHECK (generation BETWEEN 1 AND 9223372036854775807),
    state_blob BLOB NOT NULL,
    state_sha256 BLOB NOT NULL CHECK (length(state_sha256) = 32),
    PRIMARY KEY (singleton_id)
) STRICT;
