"""Shared receiver-group and node-provisioning primitives."""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import re
import secrets
import sys
import tempfile
from pathlib import Path

# Standalone source-tree tools locate their sibling runtime package. Receiver
# code imports the installed package directly and never imports this tools file.
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "python"))
from cura_protocol_v2_lora.receiver_group import (
    GROUP_STATE_FILENAME,
    GROUP_STATE_FORMAT_VERSION,
    GROUP_ID_SIZE,
    GROUP_MASTER_KEY_SIZE,
    NODE_ID_SIZE,
    ReceiverGroupState,
    ReceiverGroupRejectedError,
    load_receiver_group as _load_receiver_group,
)

NODE_IDENTITY_FILENAME = "protocol_v2_lora_identity.h"
NODE_KEY_SIZE = 16
NODE_KEY_INFO = b"cura-agrorum/protocol-v2-lora/aes-128-ccm/node-key/v1"

_NODE_ID_HEADER_RE = re.compile(
    r'^#define CURA_LORA_V2_NODE_ID_HEX "([0-9a-f]{16})"$',
    re.MULTILINE,
)
_GENERATED_HEADER_MARKER = "Generated by protocol-v2-lora/tools/provision_node.py."


class ProvisioningError(ValueError):
    """Raised when provisioning input or persistent state is unsafe."""


def require_existing_directory(path: Path, description: str) -> Path:
    resolved = path.expanduser().resolve()
    if not resolved.is_dir():
        raise ProvisioningError(
            f"{description} does not exist or is not a directory: {resolved}"
        )
    return resolved


def generate_receiver_group() -> ReceiverGroupState:
    return ReceiverGroupState(
        group_id=_random_nonzero_bytes(GROUP_ID_SIZE),
        group_master_key=secrets.token_bytes(GROUP_MASTER_KEY_SIZE),
        active_node_ids=frozenset(),
        retired_node_ids=frozenset(),
    )


def rotate_receiver_group(
    previous: ReceiverGroupState,
) -> ReceiverGroupState:
    group_id = _random_nonzero_bytes(GROUP_ID_SIZE)
    while group_id == previous.group_id:
        group_id = _random_nonzero_bytes(GROUP_ID_SIZE)

    group_master_key = secrets.token_bytes(GROUP_MASTER_KEY_SIZE)
    while group_master_key == previous.group_master_key:
        group_master_key = secrets.token_bytes(GROUP_MASTER_KEY_SIZE)

    return ReceiverGroupState(
        group_id=group_id,
        group_master_key=group_master_key,
        active_node_ids=frozenset(),
        retired_node_ids=(previous.active_node_ids | previous.retired_node_ids),
    )


def generate_unique_node_id(state: ReceiverGroupState) -> bytes:
    used = state.active_node_ids | state.retired_node_ids
    while True:
        node_id = _random_nonzero_bytes(NODE_ID_SIZE)
        if node_id not in used:
            return node_id


def derive_node_key(group_master_key: bytes, node_id: bytes) -> bytes:
    """Derive the protocol's 16-byte AES node key using HKDF-SHA-256."""
    if (
        not isinstance(group_master_key, bytes)
        or len(group_master_key) != GROUP_MASTER_KEY_SIZE
    ):
        raise ProvisioningError(
            f"group master key must be {GROUP_MASTER_KEY_SIZE} bytes"
        )
    if not isinstance(node_id, bytes) or len(node_id) != NODE_ID_SIZE:
        raise ProvisioningError(f"node ID must be {NODE_ID_SIZE} bytes")

    # RFC 5869 extract followed by the first (and only needed) expand block.
    pseudorandom_key = hmac.new(
        node_id,
        group_master_key,
        hashlib.sha256,
    ).digest()
    first_block = hmac.new(
        pseudorandom_key,
        NODE_KEY_INFO + b"\x01",
        hashlib.sha256,
    ).digest()
    return first_block[:NODE_KEY_SIZE]


def load_receiver_group(
    path: Path,
    *,
    expected_owner_uid: int | None = None,
) -> ReceiverGroupState:
    """Preserve the CLI exception API around the shared read-only loader."""
    try:
        return _load_receiver_group(path, expected_owner_uid=expected_owner_uid)
    except FileNotFoundError as exc:
        raise ProvisioningError(f"receiver group is not initialized: {path}") from exc
    except (ReceiverGroupRejectedError, OSError, TypeError, ValueError) as exc:
        raise ProvisioningError(str(exc)) from exc


def render_receiver_group(state: ReceiverGroupState) -> str:
    document = {
        "format_version": GROUP_STATE_FORMAT_VERSION,
        "group_id": state.group_id.hex(),
        "group_master_key": state.group_master_key.hex(),
        "active_node_ids": sorted(node_id.hex() for node_id in state.active_node_ids),
        "retired_node_ids": sorted(node_id.hex() for node_id in state.retired_node_ids),
    }
    return json.dumps(document, indent=2) + "\n"


def render_node_identity(node_id: bytes, node_key: bytes) -> str:
    if len(node_id) != NODE_ID_SIZE:
        raise ProvisioningError(f"node ID must be {NODE_ID_SIZE} bytes")
    if len(node_key) != NODE_KEY_SIZE:
        raise ProvisioningError(f"node key must be {NODE_KEY_SIZE} bytes")

    return f"""\
/*
 * {_GENERATED_HEADER_MARKER}
 * Contains a secret node key. Do not edit, log, or commit this file.
 */
#pragma once

#include <stdint.h>

/* Public identity retained as hex so provisioning tools can identify it. */
#define CURA_LORA_V2_NODE_ID_HEX "{node_id.hex()}"

#define CURA_LORA_V2_NODE_ID_BYTES {_c_byte_initializer(node_id)}
#define CURA_LORA_V2_NODE_KEY_BYTES {_c_byte_initializer(node_key)}
"""


def parse_node_identity_id(content: str) -> bytes:
    if _GENERATED_HEADER_MARKER not in content:
        raise ProvisioningError(
            "existing node identity was not generated by provision_node.py"
        )
    matches = _NODE_ID_HEADER_RE.findall(content)
    if len(matches) != 1:
        raise ProvisioningError("existing node identity has no unique valid node ID")
    return bytes.fromhex(matches[0])


def write_new_secret(path: Path, content: str) -> None:
    temporary = _write_temporary_secret(path, content)
    try:
        os.link(temporary, path)
        _sync_directory(path.parent)
    except FileExistsError as exc:
        raise ProvisioningError(f"refusing to overwrite existing file: {path}") from exc
    except OSError as exc:
        raise ProvisioningError(f"cannot create {path}: {exc}") from exc
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def replace_secret(path: Path, content: str) -> None:
    temporary = _write_temporary_secret(path, content)
    try:
        os.replace(temporary, path)
        _sync_directory(path.parent)
    except OSError as exc:
        raise ProvisioningError(f"cannot replace {path}: {exc}") from exc
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _random_nonzero_bytes(size: int) -> bytes:
    while True:
        value = secrets.token_bytes(size)
        if value != bytes(size):
            return value


def _c_byte_initializer(value: bytes) -> str:
    encoded = ", ".join(f"UINT8_C(0x{byte:02x})" for byte in value)
    return "{ " + encoded + " }"


def _write_temporary_secret(path: Path, content: str) -> Path:
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{path.name}.",
            dir=path.parent,
        )
    except OSError as exc:
        raise ProvisioningError(
            f"cannot create a temporary file beside {path}: {exc}"
        ) from exc

    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            descriptor = -1
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
    except (OSError, UnicodeError) as exc:
        if descriptor >= 0:
            os.close(descriptor)
        temporary.unlink(missing_ok=True)
        raise ProvisioningError(
            f"cannot write a temporary file beside {path}: {exc}"
        ) from exc
    return temporary


def _sync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
