"""Shared receiver-group and node-provisioning primitives."""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import re
import secrets
import stat
import tempfile
from dataclasses import dataclass
from pathlib import Path


GROUP_STATE_FILENAME = "receiver-group.json"
NODE_IDENTITY_FILENAME = "protocol_v2_lora_identity.h"
GROUP_STATE_FORMAT_VERSION = 1

GROUP_ID_SIZE = 8
GROUP_MASTER_KEY_SIZE = 32
NODE_ID_SIZE = 8
NODE_KEY_SIZE = 16
NODE_KEY_INFO = (
    b"cura-agrorum/protocol-v2-lora/aes-128-ccm/node-key/v1"
)

_HEX_RE = re.compile(r"^[0-9a-f]+$")
_NODE_ID_HEADER_RE = re.compile(
    r'^#define CURA_LORA_V2_NODE_ID_HEX "([0-9a-f]{16})"$',
    re.MULTILINE,
)
_GENERATED_HEADER_MARKER = (
    "Generated by protocol-v2-lora/tools/provision_node.py."
)


class ProvisioningError(ValueError):
    """Raised when provisioning input or persistent state is unsafe."""


@dataclass(frozen=True)
class ReceiverGroupState:
    group_id: bytes
    group_master_key: bytes
    active_node_ids: frozenset[bytes]
    retired_node_ids: frozenset[bytes]


def require_existing_directory(path: Path, description: str) -> Path:
    resolved = path.expanduser().resolve()
    if not resolved.is_dir():
        raise ProvisioningError(
            f"{description} does not exist or is not a directory: {resolved}"
        )
    return resolved


def generate_receiver_group() -> ReceiverGroupState:
    return ReceiverGroupState(
        group_id=_random_nonzero_bytes(GROUP_ID_SIZE),
        group_master_key=secrets.token_bytes(GROUP_MASTER_KEY_SIZE),
        active_node_ids=frozenset(),
        retired_node_ids=frozenset(),
    )


def rotate_receiver_group(
    previous: ReceiverGroupState,
) -> ReceiverGroupState:
    group_id = _random_nonzero_bytes(GROUP_ID_SIZE)
    while group_id == previous.group_id:
        group_id = _random_nonzero_bytes(GROUP_ID_SIZE)

    group_master_key = secrets.token_bytes(GROUP_MASTER_KEY_SIZE)
    while group_master_key == previous.group_master_key:
        group_master_key = secrets.token_bytes(GROUP_MASTER_KEY_SIZE)

    return ReceiverGroupState(
        group_id=group_id,
        group_master_key=group_master_key,
        active_node_ids=frozenset(),
        retired_node_ids=(
            previous.active_node_ids | previous.retired_node_ids
        ),
    )


def generate_unique_node_id(state: ReceiverGroupState) -> bytes:
    used = state.active_node_ids | state.retired_node_ids
    while True:
        node_id = _random_nonzero_bytes(NODE_ID_SIZE)
        if node_id not in used:
            return node_id


def derive_node_key(group_master_key: bytes, node_id: bytes) -> bytes:
    """Derive the protocol's 16-byte AES node key using HKDF-SHA-256."""
    if (
        not isinstance(group_master_key, bytes)
        or len(group_master_key) != GROUP_MASTER_KEY_SIZE
    ):
        raise ProvisioningError(
            f"group master key must be {GROUP_MASTER_KEY_SIZE} bytes"
        )
    if not isinstance(node_id, bytes) or len(node_id) != NODE_ID_SIZE:
        raise ProvisioningError(f"node ID must be {NODE_ID_SIZE} bytes")

    # RFC 5869 extract followed by the first (and only needed) expand block.
    pseudorandom_key = hmac.new(
        node_id,
        group_master_key,
        hashlib.sha256,
    ).digest()
    first_block = hmac.new(
        pseudorandom_key,
        NODE_KEY_INFO + b"\x01",
        hashlib.sha256,
    ).digest()
    return first_block[:NODE_KEY_SIZE]


def load_receiver_group(path: Path) -> ReceiverGroupState:
    try:
        metadata = path.stat()
    except FileNotFoundError as exc:
        raise ProvisioningError(
            f"receiver group is not initialized: {path}"
        ) from exc
    except OSError as exc:
        raise ProvisioningError(
            f"cannot inspect receiver group state {path}: {exc}"
        ) from exc

    if not stat.S_ISREG(metadata.st_mode):
        raise ProvisioningError(
            f"receiver group state is not a regular file: {path}"
        )
    if stat.S_IMODE(metadata.st_mode) & 0o077:
        raise ProvisioningError(
            f"receiver group state is accessible by group or others; "
            f"run chmod 600 {path}"
        )

    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ProvisioningError(
            f"cannot read receiver group state {path}: {exc}"
        ) from exc

    if not isinstance(document, dict):
        raise ProvisioningError("receiver group state must be a JSON object")

    expected_fields = {
        "format_version",
        "group_id",
        "group_master_key",
        "active_node_ids",
        "retired_node_ids",
    }
    if set(document) != expected_fields:
        missing = sorted(expected_fields - set(document))
        unknown = sorted(set(document) - expected_fields)
        raise ProvisioningError(
            f"receiver group state fields differ: "
            f"missing={missing}, unknown={unknown}"
        )
    if (
        type(document["format_version"]) is not int
        or document["format_version"] != GROUP_STATE_FORMAT_VERSION
    ):
        raise ProvisioningError(
            "unsupported receiver group state format_version"
        )

    group_id = _decode_hex(
        document["group_id"], GROUP_ID_SIZE, "group_id"
    )
    if group_id == bytes(GROUP_ID_SIZE):
        raise ProvisioningError("group_id must not be all zero")
    group_master_key = _decode_hex(
        document["group_master_key"],
        GROUP_MASTER_KEY_SIZE,
        "group_master_key",
    )
    active_node_ids = _decode_node_id_set(
        document["active_node_ids"], "active_node_ids"
    )
    retired_node_ids = _decode_node_id_set(
        document["retired_node_ids"], "retired_node_ids"
    )
    overlap = active_node_ids & retired_node_ids
    if overlap:
        raise ProvisioningError(
            "active_node_ids and retired_node_ids overlap: "
            + ", ".join(sorted(node_id.hex() for node_id in overlap))
        )

    return ReceiverGroupState(
        group_id=group_id,
        group_master_key=group_master_key,
        active_node_ids=frozenset(active_node_ids),
        retired_node_ids=frozenset(retired_node_ids),
    )


def render_receiver_group(state: ReceiverGroupState) -> str:
    document = {
        "format_version": GROUP_STATE_FORMAT_VERSION,
        "group_id": state.group_id.hex(),
        "group_master_key": state.group_master_key.hex(),
        "active_node_ids": sorted(
            node_id.hex() for node_id in state.active_node_ids
        ),
        "retired_node_ids": sorted(
            node_id.hex() for node_id in state.retired_node_ids
        ),
    }
    return json.dumps(document, indent=2) + "\n"


def render_node_identity(node_id: bytes, node_key: bytes) -> str:
    if len(node_id) != NODE_ID_SIZE:
        raise ProvisioningError(f"node ID must be {NODE_ID_SIZE} bytes")
    if len(node_key) != NODE_KEY_SIZE:
        raise ProvisioningError(f"node key must be {NODE_KEY_SIZE} bytes")

    return f"""\
/*
 * {_GENERATED_HEADER_MARKER}
 * Contains a secret node key. Do not edit, log, or commit this file.
 */
#pragma once

#include <stdint.h>

/* Public identity retained as hex so provisioning tools can identify it. */
#define CURA_LORA_V2_NODE_ID_HEX "{node_id.hex()}"

#define CURA_LORA_V2_NODE_ID_BYTES {_c_byte_initializer(node_id)}
#define CURA_LORA_V2_NODE_KEY_BYTES {_c_byte_initializer(node_key)}
"""


def parse_node_identity_id(content: str) -> bytes:
    if _GENERATED_HEADER_MARKER not in content:
        raise ProvisioningError(
            "existing node identity was not generated by provision_node.py"
        )
    matches = _NODE_ID_HEADER_RE.findall(content)
    if len(matches) != 1:
        raise ProvisioningError(
            "existing node identity has no unique valid node ID"
        )
    return bytes.fromhex(matches[0])


def write_new_secret(path: Path, content: str) -> None:
    temporary = _write_temporary_secret(path, content)
    try:
        os.link(temporary, path)
        _sync_directory(path.parent)
    except FileExistsError as exc:
        raise ProvisioningError(f"refusing to overwrite existing file: {path}") from exc
    except OSError as exc:
        raise ProvisioningError(f"cannot create {path}: {exc}") from exc
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def replace_secret(path: Path, content: str) -> None:
    temporary = _write_temporary_secret(path, content)
    try:
        os.replace(temporary, path)
        _sync_directory(path.parent)
    except OSError as exc:
        raise ProvisioningError(f"cannot replace {path}: {exc}") from exc
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _random_nonzero_bytes(size: int) -> bytes:
    while True:
        value = secrets.token_bytes(size)
        if value != bytes(size):
            return value


def _decode_hex(value: object, size: int, field: str) -> bytes:
    if (
        not isinstance(value, str)
        or len(value) != size * 2
        or _HEX_RE.fullmatch(value) is None
    ):
        raise ProvisioningError(
            f"{field} must contain exactly {size * 2} lowercase hex digits"
        )
    return bytes.fromhex(value)


def _decode_node_id_set(value: object, field: str) -> set[bytes]:
    if not isinstance(value, list):
        raise ProvisioningError(f"{field} must be a JSON array")

    result: set[bytes] = set()
    for index, encoded in enumerate(value):
        node_id = _decode_hex(
            encoded, NODE_ID_SIZE, f"{field}[{index}]"
        )
        if node_id == bytes(NODE_ID_SIZE):
            raise ProvisioningError(f"{field}[{index}] must not be all zero")
        if node_id in result:
            raise ProvisioningError(f"{field} contains a duplicate node ID")
        result.add(node_id)
    return result


def _c_byte_initializer(value: bytes) -> str:
    encoded = ", ".join(f"UINT8_C(0x{byte:02x})" for byte in value)
    return "{ " + encoded + " }"


def _write_temporary_secret(path: Path, content: str) -> Path:
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{path.name}.",
            dir=path.parent,
        )
    except OSError as exc:
        raise ProvisioningError(
            f"cannot create a temporary file beside {path}: {exc}"
        ) from exc

    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            descriptor = -1
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
    except (OSError, UnicodeError) as exc:
        if descriptor >= 0:
            os.close(descriptor)
        temporary.unlink(missing_ok=True)
        raise ProvisioningError(
            f"cannot write a temporary file beside {path}: {exc}"
        ) from exc
    return temporary


def _sync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
