#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "node_common.h"
#include "protocol_v2_lora_schema_generated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Packed persistence-domain errors returned by this component. */
#define CURAG_ENVS_INIT UINT32_C(0x00010001)
#define CURAG_ENVS_ACCESS UINT32_C(0x00010002)
#define CURAG_ESAMPLE_ID_EXHAUSTED UINT32_C(0x00010003)
#define CURAG_ELITTLEFS_INIT UINT32_C(0x00010004)
#define CURAG_EINVALID_ARGUMENT UINT32_C(0x00010005)
#define CURAG_EIO UINT32_C(0x00010006)
#define CURAG_ELOG_FULL UINT32_C(0x00010007)
#define CURAG_ECORRUPT_RECORD UINT32_C(0x00010008)
#define CURAG_EUNSUPPORTED_RECORD UINT32_C(0x00010009)
#define CURAG_ERECORD_MISMATCH UINT32_C(0x0001000a)
#define CURAG_EMESSAGE_ID_EXHAUSTED UINT32_C(0x0001000b)

/* Persistence diagnostic context schema and its fixed seven-byte fields. */
#define CURAG_PERSISTENCE_CONTEXT_V1 UINT8_C(1)
#define CURAG_PERSISTENCE_CONTEXT_V1_SIZE 7U

typedef uint8_t node_persistence_resource_t;
#define NODE_PERSISTENCE_RESOURCE_NONE UINT8_C(0)
#define NODE_PERSISTENCE_RESOURCE_NVS_SAMPLE_COUNTER UINT8_C(1)
#define NODE_PERSISTENCE_RESOURCE_LITTLEFS UINT8_C(2)
#define NODE_PERSISTENCE_RESOURCE_PENDING_LOG UINT8_C(3)
#define NODE_PERSISTENCE_RESOURCE_PENDING_COMPACT UINT8_C(4)
#define NODE_PERSISTENCE_RESOURCE_QUARANTINE_LOG UINT8_C(5)
#define NODE_PERSISTENCE_RESOURCE_DIAGNOSTIC_LOG UINT8_C(6)
#define NODE_PERSISTENCE_RESOURCE_DELIVERY_LOG UINT8_C(7)
#define NODE_PERSISTENCE_RESOURCE_NVS_MESSAGE_COUNTER UINT8_C(8)

typedef uint8_t node_persistence_stage_t;
#define NODE_PERSISTENCE_STAGE_NONE UINT8_C(0)
#define NODE_PERSISTENCE_STAGE_INITIALIZE UINT8_C(1)
#define NODE_PERSISTENCE_STAGE_GET UINT8_C(2)
#define NODE_PERSISTENCE_STAGE_SET UINT8_C(3)
#define NODE_PERSISTENCE_STAGE_COMMIT UINT8_C(4)
#define NODE_PERSISTENCE_STAGE_OPEN UINT8_C(5)
#define NODE_PERSISTENCE_STAGE_STAT UINT8_C(6)
#define NODE_PERSISTENCE_STAGE_READ UINT8_C(7)
#define NODE_PERSISTENCE_STAGE_WRITE UINT8_C(8)
#define NODE_PERSISTENCE_STAGE_SYNC UINT8_C(9)
#define NODE_PERSISTENCE_STAGE_TRUNCATE UINT8_C(10)
#define NODE_PERSISTENCE_STAGE_RENAME UINT8_C(11)
#define NODE_PERSISTENCE_STAGE_REMOVE UINT8_C(12)
#define NODE_PERSISTENCE_STAGE_CLOSE UINT8_C(13)
#define NODE_PERSISTENCE_STAGE_TAIL_SCAN UINT8_C(14)
#define NODE_PERSISTENCE_STAGE_QUOTA_CHECK UINT8_C(15)
#define NODE_PERSISTENCE_STAGE_ENCODE UINT8_C(16)
#define NODE_PERSISTENCE_STAGE_DECODE UINT8_C(17)

typedef uint8_t node_persistence_backend_status_kind_t;
#define NODE_PERSISTENCE_BACKEND_NO_ERROR UINT8_C(0)
#define NODE_PERSISTENCE_BACKEND_ERRNO UINT8_C(1)
#define NODE_PERSISTENCE_BACKEND_ESP_ERR UINT8_C(2)
#define NODE_PERSISTENCE_BACKEND_LITTLEFS_ERROR UINT8_C(3)

/* Flags carried by a persisted diagnostic event. */
typedef uint16_t node_diagnostic_flags_t;
#define NODE_DIAGNOSTIC_APPLICATION_OFFSET_VALID UINT16_C(0x0001)
#define NODE_DIAGNOSTIC_CYCLE_SAMPLE_ID_VALID UINT16_C(0x0002)
#define NODE_DIAGNOSTIC_MESSAGE_ID_VALID UINT16_C(0x0004)
#define NODE_DIAGNOSTIC_RESERVED_FLAGS_MASK UINT16_C(0xfff8)

/*
 * One best-effort diagnostic generated by node_core.
 *
 * error:                 Nonzero packed component error being reported.
 * flags:                 NODE_DIAGNOSTIC_* validity flags.
 * application_offset_ms: Milliseconds since application start, or zero when
 *                        its validity flag is clear.
 * cycle_sample_id:       Current wake's sample ID, or zero when its validity
 *                        flag is clear.
 * message_id:            Active logical uplink message ID, or zero when its
 *                        validity flag is clear.
 * context:               Borrowed component-produced detail. NULL encodes an
 *                        empty operation and context.
 */
typedef struct {
  err_curag_t error;
  node_diagnostic_flags_t flags;
  uint32_t application_offset_ms;
  uint32_t cycle_sample_id;
  uint32_t message_id;
  const diagn_context_t *context;
} node_diagnostic_event_t;

typedef uint8_t node_delivery_event_type_t;
#define NODE_DELIVERY_EVENT_INVALID UINT8_C(0)
#define NODE_DELIVERY_EVENT_STARTED UINT8_C(1)
#define NODE_DELIVERY_EVENT_FINISHED UINT8_C(2)

typedef uint8_t node_delivery_final_result_t;
#define NODE_DELIVERY_RESULT_INVALID UINT8_C(0)
#define NODE_DELIVERY_RESULT_ACCEPTED UINT8_C(1)
#define NODE_DELIVERY_RESULT_RETRY_LATER UINT8_C(2)
#define NODE_DELIVERY_RESULT_UNSUPPORTED UINT8_C(3)
#define NODE_DELIVERY_RESULT_MALFORMED UINT8_C(4)
#define NODE_DELIVERY_RESULT_AIRTIME_BUDGET_END UINT8_C(5)
#define NODE_DELIVERY_RESULT_RADIO_CYCLE_DEADLINE UINT8_C(6)
#define NODE_DELIVERY_RESULT_LOCAL_RADIO_ERROR UINT8_C(7)

/*
 * One durable delivery boundary event.
 *
 * type:            NODE_DELIVERY_EVENT_STARTED or _FINISHED.
 * cycle_sample_id: Sample ID claimed by the wake performing the delivery.
 * sample_id:       Sample ID of the current or backlog reading being sent.
 * message_id:      Transport-message ID of this logical uplink.
 * domain:          CURRENT_READING_UPLINK or BACKLOG_READING_UPLINK.
 * detail.started:  Application-relative start time for a STARTED event.
 * detail.finished: Wake-local attempt count and terminal result for FINISHED.
 */
typedef struct {
  node_delivery_event_type_t type;
  uint32_t cycle_sample_id;
  uint32_t sample_id;
  uint32_t message_id;
  cura_lora_v2_domain_t domain;
  union {
    struct {
      uint32_t start_offset_ms;
    } started;
    struct {
      uint8_t attempt_count;
      node_delivery_final_result_t final_result;
    } finished;
  } detail;
} node_delivery_event_t;

/*
 * Claims and durably advances the identity-lifetime sample counter.
 *
 * out_sample_id: Required caller-owned output. Written only on success.
 * out_diag:      Optional caller-owned diagnostic detail, cleared on entry.
 *
 * Fresh storage returns zero. Success guarantees that the successor was
 * committed to NVS before the claimed value was returned.
 */
err_curag_t node_persistence_claim_sample_id(uint32_t *out_sample_id,
                                             diagn_context_t *out_diag);

/* Claims and durably advances the identity/key-lifetime message counter. */
err_curag_t node_persistence_claim_message_id(uint32_t *out_message_id,
                                              diagn_context_t *out_diag);

typedef struct {
  cura_lora_v2_reading_t reading;
  bool backlog_bound;
  uint32_t message_id;
  cura_lora_v2_authenticated_reading_frame_t frame;
} node_pending_reading_t;

/* Durably appends one current reading to pending.log. */
err_curag_t
node_persistence_append_pending_reading(const cura_lora_v2_reading_t *reading,
                                        diagn_context_t *out_diag);

/* Durably binds the newest unbound reading to one exact backlog frame. */
err_curag_t node_persistence_bind_newest_backlog_frame(
    uint32_t expected_sample_id, uint32_t message_id,
    const cura_lora_v2_authenticated_reading_frame_t *frame,
    diagn_context_t *out_diag);

/*
 * Returns the newest pending reading without removing it.
 * out_found is false on a successful empty backlog; other outputs are then
 * unspecified. out_pending and out_found are required; out_diag is optional.
 */
err_curag_t
node_persistence_peek_most_recent_pending(node_pending_reading_t *out_pending,
                                          bool *out_found,
                                          diagn_context_t *out_diag);

/* Durably removes the newest pending item only if its sample ID matches. */
err_curag_t node_persistence_remove_newest_reading(uint32_t expected_sample_id,
                                                   diagn_context_t *out_diag);

/* Durably appends a permanently rejected reading to quarantine.log. */
err_curag_t
node_persistence_quarantine_reading(const cura_lora_v2_reading_t *reading,
                                    diagn_context_t *out_diag);

/* Buffers one ordinary diagnostic record for final synchronization. */
err_curag_t
node_persistence_append_diagnostic_event(const node_diagnostic_event_t *event,
                                         diagn_context_t *out_diag);

/* Durably appends one DELIVERY_STARTED or DELIVERY_FINISHED event. */
err_curag_t
node_persistence_append_delivery_event(const node_delivery_event_t *event,
                                       diagn_context_t *out_diag);

/*
 * Synchronizes remaining buffered state and closes persistence-owned handles.
 * It never initializes an unused backend and does not unmount LittleFS.
 */
err_curag_t node_persistence_sync_all(diagn_context_t *out_diag);

#ifdef __cplusplus
}
#endif
